name: travel_hour
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 3.0.0+8

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  animated_bottom_navigation_bar: ^0.3.2
  cached_network_image: ^3.2.0
  carousel_pro: ^1.0.0
  cloud_firestore: ^3.1.12
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.4
  dots_indicator: ^2.1.0
  easy_localization: any
  firebase_analytics: ^9.1.5
  firebase_auth: ^3.3.14
  firebase_core: ^1.14.1
  firebase_in_app_messaging: ^0.6.0+11
  firebase_messaging: ^11.2.13
  firebase_storage: ^10.2.12
  flare_flutter: ^3.0.2
  flutter:
    sdk: flutter
  flutter_html: ^2.2.1
  flutter_icons: ^1.1.0
  flutter_lints: ^1.0.4
  flutter_polyline_points: ^1.0.0
  flutter_staggered_animations: ^1.0.0
  flutter_widget_from_html: ^0.8.5
  geo: ^0.3.0
  google_fonts: ^2.3.1
  google_maps_flutter: ^2.1.3
  google_sign_in: ^5.3.0
  html: ^0.15.0
  html_unescape: ^2.0.0
  http: ^0.13.4
  image_picker: ^0.8.5
  intl: ^0.17.0
  launch_review: ^3.0.1
  line_icons: ^2.0.1
  md2_tab_indicator: ^1.0.2
  package_info: ^2.0.2
  provider: ^6.0.2
  share: ^2.0.4
  shared_preferences: ^2.0.13
  skeleton_text: ^3.0.0
  sliding_up_panel: ^2.0.0+1
  toast: ^0.1.5
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_launcher_icons: any
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/search.png
    - assets/images/travel1.png
    - assets/images/travel2.png
    - assets/flr/success.flr
    - assets/images/travel4.png
    - assets/images/travel5.png
    - assets/images/travel6.png
    - assets/images/empty.png
    - assets/images/restaurant.png
    - assets/images/hotel.png
    - assets/images/splash.png
    - assets/images/icon.png
    - assets/images/hotel_pin.png
    - assets/images/restaurant_pin.png
    - assets/images/destination_map_marker.png
    - assets/images/driving_pin.png
    - assets/translations/

  fonts:

    - family: Muli
      fonts:
        # - asset: fonts/Montserrat-Light.ttf
        #   weight: 400
        - asset: fonts/Muli-Regular.ttf
          weight: 500
        - asset: fonts/Muli-Medium.ttf
          weight: 600
        - asset: fonts/Muli-SemiBold.ttf
          weight: 700
        - asset: fonts/Muli-Bold.ttf
          weight: 800
